tests/test.sh

related to https://github.com/eris-ltd/eris-cli/pull/457/files

update test for eris ls funcs

---

tests/fixtures/app24/epm.yaml
tests/fixtures/app24/one.sol
tests/fixtures/app24/readme.md
tests/fixtures/app24/three.sol
tests/fixtures/app24/two.sol

multiinheritance a to b to c and test

multiInher

---

.gitignore
Godeps/Godeps.json
Godeps/_workspace/src/github.com/eris-ltd/eris-abi/abi/abi.go
Godeps/_workspace/src/github.com/eris-ltd/eris-abi/abi/lengths.go
tests/fixtures/app08/readme.md
tests/fixtures/app28/epm.yaml
tests/fixtures/app28/readme.md
tests/fixtures/app28/storage.sol
tests/fixtures/app29/epm.yaml
tests/fixtures/app29/readme.md
tests/fixtures/app29/structs0.sol
tests/fixtures/app29/structs1.sol
tests/fixtures/app29/structs10.sol
tests/fixtures/app29/structs11.sol
tests/fixtures/app29/structs2.sol
tests/fixtures/app29/structs3.sol
tests/fixtures/app29/structs4.sol
tests/fixtures/app29/structs5.sol
tests/fixtures/app29/structs6.sol
tests/fixtures/app29/structs7.sol
tests/fixtures/app29/structs8.sol
tests/fixtures/app29/structs9.sol
tests/test.sh

updates abi to include fix for dynamic argument packing -> https://github.com/eris-ltd/eris-abi/pull/17
adds test for simple (string, string) multi dynamic argument (app28)
adds test for much more complicated mixed structs scenarios (app29) 
**Special Thanks to @kootenpv for identifying the issue and crafting the base for app29**

more thoroughly test mixtures of dynamic and static types

---

circle.yml
cmd/epm.go
definitions/do.go
perform/job_manager.go
tests/fixtures/app32/app32.sol
tests/fixtures/app32/epm.yaml
tests/fixtures/app32/readme.md
tests/test.sh

Job notification

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/eris-ltd/eris-abi/abi/abi.go
Godeps/_workspace/src/github.com/eris-ltd/eris-abi/abi/type.go
Godeps/_workspace/src/github.com/eris-ltd/eris-compilers/README.md
Godeps/_workspace/src/github.com/eris-ltd/eris-compilers/compile.go
Godeps/_workspace/src/github.com/eris-ltd/mint-client/mintx/core/core.go
docs/asserts_specification.md
docs/variable_specification.md
perform/jobs_contracts.go
tests/fixtures/app30/app30.sol
tests/fixtures/app30/epm.yaml
tests/fixtures/app31/array.sol
tests/fixtures/app31/epm.yaml
tests/fixtures/app31/readme.md
util/readers.go

This enables us to handle arrays. Documentation is coming. Solves part of issue #87 and gets the ball rolling there.

Array handling

---

tests/fixtures/app33/epm.yaml
tests/fixtures/app33/permissions.sol
tests/fixtures/app33/readme.md
tests/test.sh

Test SNatives -> EVM

---

Dockerfile
circle.yml
glide.lock
glide.yaml
perform/jobs_contracts.go

Signed-off-by: VoR0220 <catalanor0220@gmail.com>
vendor update
Signed-off-by: VoR0220 <catalanor0220@gmail.com>
testing compilers
Signed-off-by: VoR0220 <catalanor0220@gmail.com>
finally working! WOOHOO
Signed-off-by: VoR0220 <catalanor0220@gmail.com>
fixup test
Signed-off-by: VoR0220 <catalanor0220@gmail.com>
Now onto fix the libraries.

Enables EPM to work with the new compilers

---

glide.lock

Signed-off-by: VoR0220 <catalanor0220@gmail.com>

change warn and debug message

---

perform/jobs_contracts.go

Signed-off-by: VoR0220 <catalanor0220@gmail.com>

do better job error handling

---

tests/test.sh

for https://github.com/eris-ltd/eris-cli/pull/785

skip build for eris-cli

---

circle.yml
cmd/epm.go
docs/generator.go
packages/load_package.go
perform/job_manager.go
perform/jobs_contracts.go
perform/jobs_test_jobs.go
perform/jobs_transact.go
perform/jobs_util.go
util/chain_info.go
util/errors.go
util/readers.go
util/variables.go
util/writers.go

Use eris logger

---

perform/job_manager.go
util/readers.go
util/writers.go

notify of epm.json/csv output with verbose flag

---

glide.lock
perform/job_manager.go

fix the y/n hang, replace with func from /common

---

README.md

Glide Installation Instructions added to README

---

glide.lock

Add updated compilers

---

Dockerfile

* fixes #183 
* todo: need to figure out how to port this to alpine for maximum smallness (ain't that something of an oxymoron?)
* overall: makes our image small again.

Clean Vendor

---

Dockerfile.armhf

Forgot to add vendor clean for arm as well

---

glide.lock
perform/jobs_contracts.go

*solves the problems in #188 if a tad crudely (double printing of the error), but at the very least it will work for now until we decide on a better way to format this.

Better logging errors

---

docs/variable_specification.md
perform/jobs_contracts.go
tests/fixtures/app37-fallback_function/epm.yaml
tests/fixtures/app37-fallback_function/fallback.sol
tests/fixtures/app37-fallback_function/readme.md

* implements support for fallback function
* closes #178

finalize the fallback function

---

docs/jobs_specification.md
docs/variable_specification.md

minor updates to documentation

updates to documentation

---

Dockerfile
Dockerfile.armhf
README.md
circle.yml
cmd/epm.go
docs/examples/deploying_your_smart_contracts_to_a_chain_advanced.md
tests/docker.sh

- s/eris.industries/monax.io wherever applicable
- Other minor rebrand edits.

update compilers URL, Dockerfiles, & other links

---

.gitignore
Dockerfile_outsidebuild
circle.yml
tests/build_outside_tool.sh
tests/test.sh

- addresses docker image size indirectly and avoids glide conflict inside docker

PROPOSAL docker: build outside of docker

---

circle.yml

fix the previous way

---

README.md

s/epm/eris-pm/g and a few other fixups.

readme fixups

---

perform/jobs_test_jobs.go

Fixes problem on query jobs as specified here. eris-ltd/eris-cli#1046

fix printing on query jobs

---

glide.lock
glide.yaml

fixes https://github.com/eris-ltd/eris-cli/issues/1041

glide: update glide to point to eris-db develop

---

abi/core.go
abi/core_test.go
circle.yml
definitions/jobs.go
docs/generator.go
perform/jobs_contracts.go
perform/jobs_test_jobs.go
perform/jobs_transact.go
tests/fixtures/app08-initialization_constructors_in_contracts/contracts/storage.sol
tests/fixtures/app08-initialization_constructors_in_contracts/epm.yaml
util/chain_info.go
util/readers.go
util/variables.go

* fixes https://github.com/eris-ltd/eris-cli/issues/1065
* gets deploy jobs using the same code as call and query jobs for preprocessing (thus making it look cleaner)
* gets ABI to handle the case of a constructor in core.go
* fleshes out constructor tests to test for multiple types and different methods of input in a epm.yaml file.
Signed-off-by: VoR0220 <rj@erisindustries.com>

Fix problems with Constructor Calls and make Constructor tests more thorough

---

glide.lock
glide.yaml
perform/job_manager.go
perform/jobs_contracts.go

Fix output
